# simple dockerfile to test OCP s2i using Dockerfile 

FROM registry.access.redhat.com/ubi7:latest

# CMD ["/bin/bash", "-c", "sleep infinity"]
CMD ["/bin/bash", "-c", "--","while true; do sleep 35; echo "hello"; done;"]

# CMD changed to create a change in the Dockerfile
